[workspace]
resolver = "2"
members = [
    "asciifier",
    "egui_app",
    "examples/*"
]


[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
asciifier = { path = "asciifier" }

[profile.release]
opt-level = 3
